- name: Install vim
  yum:
    name: "vim"
    state: present

- name: Install epel
  yum:
    name: "epel-release"
    state: present

- name: Install python36
  yum:
    name: "python36"
    state: present
